init
kakao-tech-campus-2nd-step3/Team2_FE pull request #1
Opened 2024-09-11 06:10 UTC by dandamdandam

- vite
- emotion style
- stylebook

- eslint, prettier

- reset css, google material icon

2024-09-11 07:09 UTC, dandamdandam commented
@jjh4450

2024-09-12 06:05 UTC, jjh4450 requested changes
ts 사용 여부 프런트 간 합의하셨나요? 그 부분만 수행됐으면 상관은 없을 거 같습니다.

2024-09-12 06:15 UTC, jjh4450 approved these changes
수고하셨습니다!

2024-09-12 06:15 UTC, merged

2024-09-12 06:17 UTC, jjh4450 commented
init 관련해서 사소하게 수정할 거 생기면(readme, 폴더 이름 변경 등) 따로 pr 없이 바로바로 머지 하셔도 상관없습니다! 본격적으로 프로젝트 시작하기 전에 통합적으로 볼게요.