feat: Footer 구현
kakao-tech-campus-2nd-step3/Team2_FE pull request #11
Opened 2024-10-01 05:39 UTC by codus1718

2024-10-01 05:47 UTC, dandamdandam commented
https://github.com/kakao-tech-campus-2nd-step3/Team2_FE/pull/10#issuecomment-2384849530

2024-10-01 05:53 UTC, dandamdandam commented
![image](https://github.com/user-attachments/assets/d633f226-7874-4ff3-8fd0-d54fe3fb0f24)
헤더 오른쪽 상단 버튼들의 라우팅 path가 잘못되어 있는 듯 합니당
/store -> /products, /news/columns로 바꿔주세요

https://github.com/kakao-tech-campus-2nd-step3/Team2_FE/blob/feat/footer/src/utils/path.ts 이거 참조해서 작업해도 좋을 것 같아요!

2024-10-01 06:00 UTC, dandamdandam requested changes
고생하셨습니다~ 코멘트단 여유되면 코맨트 단 몇 개 수정해주세요

2024-10-01 06:00 UTC, dandamdandam commented on src/components/Layout/index.tsx
>        Layout
제가 테스트 용으로 넣어뒀던 글자라 언젠간 지워야하는데
혹시 대신 지워주실 수 있나요?

2024-10-01 06:00 UTC, dandamdandam commented on src/components/Layout/index.tsx
> +      <Footer />
디자인을 보면 홈, 로그인, 마이페이지에는 푸터가 안들어갑니다!

useLocation 훅인가? 그거 사용해서 현재 페이지에 홈, 로그인, 마이페이지일 경우 푸터를 랜더링 하니 않게 만들면 좋을 것 같아요

2024-10-01 06:18 UTC, codus1718 commented on src/components/Layout/index.tsx
>        Layout
Outlet 말씀하시는거죠? 알겠습니당

2024-10-02 02:07 UTC, jjh4450 commented on src/components/Layout/index.tsx
> +      <Footer />
#12

2024-10-02 02:07 UTC, jjh4450 commented
> ![image](https://private-user-images.githubusercontent.com/102032954/372336079-d633f226-7874-4ff3-8fd0-d54fe3fb0f24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MzUxMzcsIm5iZiI6MTcyNzgzNDgzNywicGF0aCI6Ii8xMDIwMzI5NTQvMzcyMzM2MDc5LWQ2MzNmMjI2LTc4NzQtNGZmMy04ZmQwLWQ1NGZlM2ZiMGYyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQwMjA3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTdhMWJiNWJiMWE0MTYyYjk1ZTczNGUyYTQ1NWJlYzU0OWU4M2M2ZTM0YmJjNGEzMTM0MWVmNjIxMjU4MmFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EXMxpcxz1iWpyaXtcfFGy43V1GirW-yUeinXZP9CArw) 헤더 오른쪽 상단 버튼들의 라우팅 path가 잘못되어 있는 듯 합니당 /store -> /products, /news -> /columns로 바꿔주세요
> 
> https://github.com/kakao-tech-campus-2nd-step3/Team2_FE/blob/feat/footer/src/utils/path.ts 이거 참조해서 작업해도 좋을 것 같아요!

#12

2024-10-08 02:02 UTC, dandamdandam commented
[프리뷰](https://kakao-team2-fe-git-feat-footer-jeong-dayeons-projects.vercel.app/)

2024-10-09 12:26 UTC, dandamdandam commented on src/components/Layout/index.tsx
> +      <Footer />
추후 수정 예정

2024-10-09 12:31 UTC, dandamdandam approved these changes
고생하셨다!

2024-10-09 12:32 UTC, merged