강원대 2조 6주차 코드리뷰 요청
kakao-tech-campus-2nd-step3/Team2_FE pull request #29
Opened 2024-10-11 15:29 UTC by dandamdandam

이번 주차에는 Header, Footar, ColumnList의 일부를 구현했습니다.
잘부탁드립니다!

2024-10-13 01:45 UTC, taehwanno requested changes
고생하셨습니다. 피드백 드려요.

2024-10-13 01:45 UTC, taehwanno commented on package.json
> +      "npm run prettier-check"
lint-staged에서 실행할 떄는 포맷팅이 되지 않은 코드가 있다면 바로 수정될 수 있게 prettier --write 적용하는걸 추천드려요. 포맷팅 되지 않은 코드 발견하면 지금은 커밋하다가 에러만 발생하고 다시 확인 후 적용해야할 거라서요.

2024-10-13 01:45 UTC, taehwanno commented on README.md
> +  - 제가 만든 것의 반대도 가능하겠다고 생각했습니다. (ColumnList에서 상태와 상태변경 함수를 만들어 SortingBtns 컴포넌트의 Props로 넣어주기). 그런데 이러면 SortingBtns의 독립성이 없어질 것 같아요.
GET 요청과 관련된 속성이라 페이지 URL에 query string으로 추가해준다면 react-router-dom의 useSearchParams 사용해서 상태를 소비하면 되지 않을까 싶은데 어떤 어려움이 있으신가요?

2024-10-13 01:45 UTC, taehwanno commented on src/utils/hooks/useQueryParam.ts
> +};
useQueryParam는 만들지 않고 useSearchParams를 바로 사용하면 되지 않을까 싶은데 만드신 이유가 궁금합니다.

2024-10-13 01:45 UTC, taehwanno commented on src/pages/ColumnList/useSortingBtns.tsx
> +}
useSortingBtns는 어떤 목적으로 만들게 됐나요? 따로 분리하지 않고 간단하게 ColumnList에서 구현해도 되지 않을까 싶습니다.

2024-10-13 04:17 UTC, dandamdandam commented on package.json
> +      "npm run prettier-check"
반영하겠습니다!

2024-10-13 04:42 UTC, dandamdandam commented on src/pages/ColumnList/useSortingBtns.tsx
> +}
두 가지 이유로 나누었습니다.
1. 지금은 컬럼 리스트 페이지에만 존재하지만, 추후 이 컴포넌트가 상품 리스트 페이지에서도 쓰일 가능성이 있습니다.
2. 개인적으로 index 파일을 깔끔하게 유지하는 걸 좋아합니다. 짧은 코드지만 map이나 style 같이 다른 키워드가 들어가는 것보단, <SortingBtns /> 한 줄이 들어가는게 페이지에 뭐가 있는지 한눈에 파악하게 좋겠다는 생각을 했습니다!

2024-10-13 04:42 UTC, dandamdandam commented on src/utils/hooks/useQueryParam.ts
> +};
해당 컴포넌트는 activeState와 query parameter를 동기화하는 일을 합니다.
이는 사용자 경험을 높이기 위해서인데요, 예를 들어서, 페이지네이션을 5번에 해두고(`/columns?pageToken=5`) 컬럼요소를 눌러 컬럼 페이지(`/columns/29395`)로 이동했다가 다시 돌아올 때 5번 페이지네이션 창으로 다시 돌아가게 합니다.

이러한 작업이 SortingBtns 뿐만 아니라, 페이지네이션 컴포넌트나 검색창 등 다양하게 사용될 수 있겠다고 생각해서 커스텀 훅을 만들었습니다.

2024-10-13 04:42 UTC, dandamdandam commented on README.md
> +  - 제가 만든 것의 반대도 가능하겠다고 생각했습니다. (ColumnList에서 상태와 상태변경 함수를 만들어 SortingBtns 컴포넌트의 Props로 넣어주기). 그런데 이러면 SortingBtns의 독립성이 없어질 것 같아요.
확실히 useSearchParams를 사용하면 컴포넌트 사이에서 state를 넘겨줄 필요는 없겠네요...! 생각도 못하고 있었습니다 반영해보겠습니다!

2024-10-14 14:24 UTC, taehwanno approved these changes
기간상 병합해두겠습니다. 고생하셨어요!

2024-10-14 14:24 UTC, merged